package ebpf

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"strings"
	"syscall"
)

// ZaskInodeKey uniquely identifies a file by inode number and device.
// Kept for debugging and informational logging; no longer used as the
// verdict map key after Phase 3c (use ZaskExecKey for enforcement).
type ZaskInodeKey struct {
	InodeNumber uint64
	DeviceId    uint32
}

// ZaskHashKey is a SHA-256 file hash.
// Used for single-binary content identity: ComputeFileHash, script hashing,
// and as components of ZaskExecKey. Moved from auto-generated code (was
// bpf2go -type hash_key) to this file when the verdict map key changed to
// the compound ZaskExecKey (Phase 3c ADR).
type ZaskHashKey struct {
	Hash [32]uint8
}

// ZaskExecKey is the verdict map key — generated by bpf2go from the C
// struct exec_key. Kept here as documentation only; the canonical definition
// lives in the generated zask_bpfel.go. The compound key encodes WHO invokes
// WHAT: (parent_binary_hash, child_binary_hash) → verdict. When parent_hash
// is all-zeros it is the unknown-parent sentinel (parent started before ZASK).

// ResolvePathToInode translates an absolute file path to its underlying
// inode_number and device_id. Symlinks are resolved to their target.
// NOTE: Results are informational only (§3c.3.5). For enforcement, use
// ComputeFileHash to get the content-derived identity.
func ResolvePathToInode(path string) (ZaskInodeKey, error) {
	var stat syscall.Stat_t
	if err := syscall.Stat(path, &stat); err != nil {
		return ZaskInodeKey{}, fmt.Errorf("stat %s: %w", path, err)
	}
	return ZaskInodeKey{
		InodeNumber: stat.Ino,
		DeviceId:    uint32(stat.Dev),
	}, nil
}

// ComputeFileHash computes the SHA-256 hash of a file's contents and
// returns it as a ZaskHashKey for verdict map operations. This is the
// userspace equivalent of the kernel's bpf_ima_file_hash() for scripts
// and other files not measured by IMA's bprm hook.
func ComputeFileHash(path string) (ZaskHashKey, error) {
	f, err := os.Open(path)
	if err != nil {
		return ZaskHashKey{}, fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return ZaskHashKey{}, fmt.Errorf("hash %s: %w", path, err)
	}

	var key ZaskHashKey
	copy(key.Hash[:], h.Sum(nil))
	return key, nil
}

// FindScriptPath reads /proc/[pid]/cmdline and returns the first argument
// that looks like a file path (starts with '/' or './'). This handles
// interpreters invoked with flags before the script path, e.g.:
//
//	python3 -u /tmp/evil.py  → "/tmp/evil.py"
//	bash -c "rm -rf /"      → "" (no path-like arg)
//	node ./app.js            → "./app.js"
//
// Returns "" if the process has exited or no path-like argument is found.
// The pid 0 is never read (kernel idle).
func FindScriptPath(pid uint32) string {
	if pid == 0 {
		return ""
	}
	data, err := os.ReadFile(fmt.Sprintf("/proc/%d/cmdline", pid))
	if err != nil {
		return "" // process already exited — non-fatal
	}
	// cmdline is NUL-separated: ["python3", "-u", "/tmp/evil.py", ""]
	args := bytes.Split(data, []byte{0})
	// Skip argv[0] (the interpreter itself), scan remaining args.
	if len(args) > 1 {
		return findScriptInArgs(args[1:])
	}
	return ""
}

// findScriptInArgs scans a list of command-line arguments (already split)
// and returns the first that looks like a script path, skipping flags.
func findScriptInArgs(args [][]byte) string {
	for _, arg := range args {
		s := string(arg)
		if s == "" {
			continue
		}
		// Skip flags (args starting with '-').
		if strings.HasPrefix(s, "-") {
			continue
		}
		// Accept arguments that look like file paths.
		if strings.HasPrefix(s, "/") || strings.HasPrefix(s, "./") || strings.HasPrefix(s, "../") {
			return s
		}
		// Also accept bare filenames (e.g., "script.py") — the first
		// non-flag argument is likely the script in most interpreter
		// invocations. Stop at the first candidate.
		return s
	}
	return ""
}
